{{- if .Values.planetmint.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: planetmint-tendermint
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: rddl-explorer
    app.kubernetes.io/name: planetmint
spec:
  accessModes:
    - {{ .Values.planetmint.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.planetmint.persistence.tendermint.size | quote }}
  storageClassName: {{ .Values.planetmint.persistence.storageClassName | quote }}
{{- end -}}
